name: emt_patientview
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  #body_part_selector: ^0.2.0
  collection: ^1.18.0
  fhir: ^0.12.0
  file_saver: ^0.2.14
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  #flutter_bloc: ^9.0.0
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  flutter_to_pdf: ^0.3.0

 # group_button: ^5.3.4
  http: ^1.3.0
  material_symbols_icons: ^4.2801.1
  provider: ^6.1.2
  shared_preferences: ^2.3.5
 # speech_to_text: ^7.0.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  dependency_validator: ^3.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: MavenJohanniter
      fonts:
        - asset: assets/fonts/MavenJohanniter-Regular.ttf
        - asset: assets/fonts/MavenJohanniter-Bold.ttf
          weight: 700
        # - asset: assets/fonts/MavenJohanniter-Medium.ttf
        #   style: medium
        # - asset: assets/fonts/MavenJohanniter-SemiBold.ttf
        #   style: semibold
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
