ame: Flutter Web Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web

    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build
        path: build/web
      
    - name: Github Actions Create Release
      uses: idev-coder/github-actions-release@v1.0.0
      with:
          tag_name: ${{ github.ref }}
          name: web-build
          path: build/web
