name: Flutter Web Build

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web --profile --dart-define=Dart2jsOptimization=O0

    - name: Zip build artifacts
      run: zip -r web-build.zip build/web

    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build
        path: build/web

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.4
        release_name: "Release v1.0.4"  
        body: 'Release of the Flutter web application'
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: web-build.zip  # Path to the zipped file
        asset_name: web-build.zip
        asset_content_type: application/zip
